import express from "express";
import { createServer as createViteServer } from "vite";
import path from "path";
import { fileURLToPath } from "url";
import nodemailer from "nodemailer";
import dotenv from "dotenv";

dotenv.config();

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

async function startServer() {
  const app = express();
  const PORT = 3000;

  app.use(express.json());

  // API Route for Inquiry Notification
  app.post("/api/notify", async (req, res) => {
    const { name, company, email, phone, type, content } = req.body;

    if (!name || !email || !content) {
      return res.status(400).json({ error: "Missing required fields" });
    }

    try {
      // Check if SMTP credentials are provided
      if (!process.env.SMTP_USER || !process.env.SMTP_PASS) {
        console.warn("⚠️ SMTP Credentials (SMTP_USER, SMTP_PASS) are missing. Email notification skipped.");
        console.warn("Please set these in the Settings menu to receive email alerts.");
        return res.status(200).json({ 
          success: false, 
          message: "Database saved, but email service not configured." 
        });
      }

      // Setup Nodemailer
      const transporter = nodemailer.createTransport({
        host: process.env.SMTP_HOST || "smtp.gmail.com",
        port: parseInt(process.env.SMTP_PORT || "587"),
        secure: process.env.SMTP_PORT === "465",
        auth: {
          user: process.env.SMTP_USER,
          pass: process.env.SMTP_PASS,
        },
      });

      const recipient = process.env.NOTIFICATION_EMAIL || "999c@kakao.com";
      const mailOptions = {
        from: `"Yours Web Inquiry" <${process.env.SMTP_USER}>`,
        to: recipient,
        subject: `[Yours Web Inquiry] ${company} - From ${name}`,
        text: `
A new project inquiry has been received.

Name: ${name}
Company: ${company}
Email: ${email}
Phone: ${phone}
Type: ${type}
Message:
${content}
        `,
        html: `
          <div style="font-family: sans-serif; max-width: 600px; margin: 0 auto; border: 1px solid #e5e9f0; border-radius: 8px; overflow: hidden;">
            <div style="background: #0A2540; color: white; padding: 24px; text-align: center;">
              <h2 style="margin: 0;">New Project Inquiry</h2>
            </div>
            <div style="padding: 24px;">
              <table style="width: 100%; border-collapse: collapse;">
                <tr><td style="padding: 8px 0; border-bottom: 1px solid #f0f0f0;"><strong>Name:</strong></td><td style="padding: 8px 0; border-bottom: 1px solid #f0f0f0;">${name}</td></tr>
                <tr><td style="padding: 8px 0; border-bottom: 1px solid #f0f0f0;"><strong>Company:</strong></td><td style="padding: 8px 0; border-bottom: 1px solid #f0f0f0;">${company}</td></tr>
                <tr><td style="padding: 8px 0; border-bottom: 1px solid #f0f0f0;"><strong>Email:</strong></td><td style="padding: 8px 0; border-bottom: 1px solid #f0f0f0;">${email}</td></tr>
                <tr><td style="padding: 8px 0; border-bottom: 1px solid #f0f0f0;"><strong>Phone:</strong></td><td style="padding: 8px 0; border-bottom: 1px solid #f0f0f0;">${phone}</td></tr>
                <tr><td style="padding: 8px 0; border-bottom: 1px solid #f0f0f0;"><strong>Type:</strong></td><td style="padding: 8px 0; border-bottom: 1px solid #f0f0f0;">${type}</td></tr>
              </table>
              <div style="margin-top: 24px; padding: 16px; background: #f8fafc; border-radius: 4px; border-left: 4px solid #3B6EFF;">
                <p style="margin: 0; font-weight: bold; color: #0A2540; margin-bottom: 8px;">Message:</p>
                <div style="color: #4a5468; line-height: 1.6;">${content.replace(/\n/g, "<br>")}</div>
              </div>
            </div>
            <div style="background: #f8fafc; padding: 16px; text-align: center; border-top: 1px solid #e5e9f0;">
              <p style="margin: 0; font-size: 12px; color: #8a94a6;">This message was automatically generated by Yours Web System.</p>
            </div>
          </div>
        `,
      };

      await transporter.sendMail(mailOptions);
      console.log("✅ Inquiry email notification sent successfully to", recipient);
      res.json({ success: true });
    } catch (error) {
      console.error("❌ Failed to send inquiry email:", error);
      res.status(500).json({ error: "Email service failed" });
    }
  });

  // Vite middleware for development
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), "dist");
    app.use(express.static(distPath));
    app.get("*", (req, res) => {
      res.sendFile(path.join(distPath, "index.html"));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Server running on http://localhost:${PORT}`);
  });
}

startServer();
